#!/usr/bin/env python3
"""Generate smoke-test fixtures from compat/golden.json.

Writes, relative to this script:
  sheet.yaml        — the golden sheet in canonical YAML form (what
                      quilt_engine_load_sheet consumes)
  golden_vectors.h  — C constants for the golden seals / reconcile fields
                      (what smoke/smoke.c asserts against)

Single source of truth: ../../compat/golden.json. Never hand-edit the
outputs; re-run this instead. Run from anywhere:
  python3 crates/quilt-cabi/smoke/gen-sheet.py
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GOLDEN = os.path.normpath(os.path.join(HERE, "..", "..", "..", "compat", "golden.json"))


def yaml_value(v):
    """Render a JSON value as a YAML scalar (json.dumps is valid YAML)."""
    return json.dumps(v)


def yaml_string(s):
    return json.dumps(s)


def gen_sheet_yaml(g):
    sheet = g["sheet"]
    lines = [
        "# GENERATED by smoke/gen-sheet.py from compat/golden.json — do not edit.",
        "# The golden sheet; every cell id, kind, and dependency edge is part",
        "# of the quilt-compat/1 contract.",
        f"id: {yaml_string(sheet['id'])}",
        f"description: {yaml_value(sheet['description'])}",
        "cells:",
    ]
    for cell in sheet["cells"]:
        lines.append(f"  - id: {yaml_string(cell['id'])}")
        lines.append(f"    kind: {yaml_string(cell['kind'])}")
        for key in ("source", "default", "value", "expr"):
            if key in cell:
                lines.append(f"    {key}: {yaml_value(cell[key])}")
    return "\n".join(lines) + "\n"


def c_string_literal(s):
    body = s.replace("\\", "\\\\").replace('"', '\\"')
    return "\n".join(f'    "{line}\\n"' for line in body.split("\n")[:-1])


def short(num):
    """Shortest round-trip decimal for a golden float (ryu/python agree)."""
    f = float(num)
    return repr(f) if f != int(f) else f"{f}.0"


def gen_golden_header(g):
    op_e = g["op_e_chain"]
    entries = op_e["entries"]
    rec = op_e["reconcile"]
    cell = op_e["transcript"]["cell"]
    needles = [
        f'\\"cell_id\\":\\"{cell}\\"',
        f'\\"entries\\":{rec["entries"]}',
        f'\\"open_inputs\\":{rec["open_inputs"]}',
        f'\\"matched_pairs\\":{rec["matched_pairs"]}',
        f'\\"chain_intact\\":{str(rec["chain_intact"]).lower()}',
        f'\\"continuity_intact\\":{str(rec["continuity_intact"]).lower()}',
        f'\\"balanced\\":{str(rec["balanced"]).lower()}',
        f'\\"total_surprise\\":{short(rec["total_surprise"])}',
        f'\\"mean_surprise\\":{short(rec["mean_surprise"])}',
    ]
    needles_c = "\n".join(f'    "{n}",' for n in needles)
    return f"""/* GENERATED by smoke/gen-sheet.py from compat/golden.json — do not edit. */
#ifndef QUILT_GOLDEN_VECTORS_H
#define QUILT_GOLDEN_VECTORS_H

/* The golden sheet, YAML form (op sheet / a / b). */
static const char *SHEET_YAML =
{c_string_literal(gen_sheet_yaml(g))};

/* op_e_chain: per-entry seals and the genesis root, bit-for-bit. */
static const char *G_ENTRY1_PREV = "{entries[0]['prev_hash']}";
static const char *G_ENTRY1 = "{entries[0]['hash']}";
static const char *G_ENTRY2 = "{entries[1]['hash']}";
static const char *G_ENTRY3 = "{entries[2]['hash']}";
static const char *G_CHAIN_HASH = "{op_e['chain_hash']}";

/* op_e reconcile: substrings the JSON report must contain. NULL-ended. */
static const char *G_RECONCILE_NEEDLES[] = {{
{needles_c}
    NULL}};

#endif /* QUILT_GOLDEN_VECTORS_H */
"""


def main():
    with open(GOLDEN) as f:
        g = json.load(f)
    if g.get("contract") != "quilt-compat/1":
        sys.exit(f"unexpected contract {g.get('contract')!r}; fail loudly, never guess")
    with open(os.path.join(HERE, "sheet.yaml"), "w") as f:
        f.write(gen_sheet_yaml(g))
    with open(os.path.join(HERE, "golden_vectors.h"), "w") as f:
        f.write(gen_golden_header(g))
    print("generated: sheet.yaml, golden_vectors.h (from compat/golden.json)")


if __name__ == "__main__":
    main()
