/* GENERATED by smoke/gen-sheet.py from compat/golden.json — do not edit. */
#ifndef QUILT_GOLDEN_VECTORS_H
#define QUILT_GOLDEN_VECTORS_H

/* The golden sheet, YAML form (op sheet / a / b). */
static const char *SHEET_YAML =
    "# GENERATED by smoke/gen-sheet.py from compat/golden.json — do not edit.\n"
    "# The golden sheet; every cell id, kind, and dependency edge is part\n"
    "# of the quilt-compat/1 contract.\n"
    "id: \"bilge-reflex\"\n"
    "description: \"The golden sheet: a sensor, a threshold, two formulas, a status value. Every cell id, kind, and dependency edge below is part of the contract.\"\n"
    "cells:\n"
    "  - id: \"bilge.level\"\n"
    "    kind: \"sensor\"\n"
    "    source: \"simulated\"\n"
    "    default: 40.0\n"
    "  - id: \"bilge.threshold\"\n"
    "    kind: \"value\"\n"
    "    value: 80.0\n"
    "  - id: \"pump.should_run\"\n"
    "    kind: \"formula\"\n"
    "    expr: \"=bilge.level >= bilge.threshold\"\n"
    "  - id: \"pump.relay_cmd\"\n"
    "    kind: \"formula\"\n"
    "    expr: \"=clamp((bilge.level - bilge.threshold) * 0.5, -30.0, 30.0)\"\n"
    "  - id: \"status\"\n"
    "    kind: \"value\"\n"
    "    value: \"idle\"\n";

/* op_e_chain: per-entry seals and the genesis root, bit-for-bit. */
static const char *G_ENTRY1_PREV = "470bc52774d2c173c46c5b0a8733676500fbc3b0b0cbf6d3e57662ff2ac4c1d3";
static const char *G_ENTRY1 = "00b88886f4a22747e7e546144d18af42605c34e2ba07d3040ba18d6f24ce3f30";
static const char *G_ENTRY2 = "3f3a94eb2e88c0e3bddfc8dfcb5554af2fe7b5cd80e20ac0ff972ae7a31caa3d";
static const char *G_ENTRY3 = "4a7ad64830d5c2a843bf7b6f4d7253d43f2603753611fe58f0bb7c4d87ea62b8";
static const char *G_CHAIN_HASH = "4a7ad64830d5c2a843bf7b6f4d7253d43f2603753611fe58f0bb7c4d87ea62b8";

/* op_e reconcile: substrings the JSON report must contain. NULL-ended. */
static const char *G_RECONCILE_NEEDLES[] = {
    "\"cell_id\":\"bilge.level\"",
    "\"entries\":3",
    "\"open_inputs\":0",
    "\"matched_pairs\":3",
    "\"chain_intact\":true",
    "\"continuity_intact\":true",
    "\"balanced\":true",
    "\"total_surprise\":47.5",
    "\"mean_surprise\":15.833333333333334",
    NULL};

#endif /* QUILT_GOLDEN_VECTORS_H */
