package quiltffi

import (
	"crypto/sha256"
	"encoding/hex"
	"math"
	"strings"
	"testing"
)

// Golden vectors from compat/golden.json (mirror of the generated
// crates/quilt-cabi/smoke/golden_vectors.h — never hand-derived).
const sheetYAML = `# GENERATED by smoke/gen-sheet.py from compat/golden.json — do not edit.
# The golden sheet; every cell id, kind, and dependency edge is part
# of the quilt-compat/1 contract.
id: "bilge-reflex"
description: "The golden sheet: a sensor, a threshold, two formulas, a status value. Every cell id, kind, and dependency edge below is part of the contract."
cells:
  - id: "bilge.level"
    kind: "sensor"
    source: "simulated"
    default: 40.0
  - id: "bilge.threshold"
    kind: "value"
    value: 80.0
  - id: "pump.should_run"
    kind: "formula"
    expr: "=bilge.level >= bilge.threshold"
  - id: "pump.relay_cmd"
    kind: "formula"
    expr: "=clamp((bilge.level - bilge.threshold) * 0.5, -30.0, 30.0)"
  - id: "status"
    kind: "value"
    value: "idle"
`

const (
	gGenesisRoot = "470bc52774d2c173c46c5b0a8733676500fbc3b0b0cbf6d3e57662ff2ac4c1d3"
	gEntry1      = "00b88886f4a22747e7e546144d18af42605c34e2ba07d3040ba18d6f24ce3f30"
	gEntry2      = "3f3a94eb2e88c0e3bddfc8dfcb5554af2fe7b5cd80e20ac0ff972ae7a31caa3d"
	gEntry3      = "4a7ad64830d5c2a843bf7b6f4d7253d43f2603753611fe58f0bb7c4d87ea62b8"
	gChainHash   = "4a7ad64830d5c2a843bf7b6f4d7253d43f2603753611fe58f0bb7c4d87ea62b8"
)

var gReconcileNeedles = []string{
	`"cell_id":"bilge.level"`,
	`"entries":3`,
	`"open_inputs":0`,
	`"matched_pairs":3`,
	`"chain_intact":true`,
	`"continuity_intact":true`,
	`"balanced":true`,
	`"total_surprise":47.5`,
	`"mean_surprise":15.833333333333334`,
}

// op (d) wire-edge helpers (edge_schema_v 1), mirroring the wasm-tier
// conformance pattern (crates/quilt-core-wasm/tests/wasm_conformance.rs
// op (d)): delta is componentwise after-before, scalar imbalance is
// |after-before|, vector imbalance is the L2 norm, null prior -> null.
func wireDeltaScalar(before, after float64) float64 { return after - before }

func wireImbalanceScalar(before, after float64) float64 {
	return math.Abs(after - before)
}

func wireDeltaVector(before, after []float64) []float64 {
	out := make([]float64, len(before))
	for i := range before {
		out[i] = after[i] - before[i]
	}
	return out
}

func wireImbalanceVector(before, after []float64) float64 {
	sum := 0.0
	for i := range before {
		d := after[i] - before[i]
		sum += d * d
	}
	return math.Sqrt(sum)
}

// provenance = sha256_hex(canonical_json(inputs)); the golden inputs are
// already in canonical form (compact, ryu shortest-round-trip floats).
func provenance(canonicalInputs string) string {
	sum := sha256.Sum256([]byte(canonicalInputs))
	return hex.EncodeToString(sum[:])
}

func newGoldenEngine(t *testing.T) *Engine {
	t.Helper()
	e, err := EngineNew()
	if err != nil {
		t.Fatalf("engine_new: %v", err)
	}
	t.Cleanup(e.Free)
	if err := e.LoadSheet(sheetYAML); err != nil {
		t.Fatalf("load_sheet (golden YAML): %v", err)
	}
	return e
}

func getIs(t *testing.T, e *Engine, cell, want string) {
	t.Helper()
	got, err := e.Get(cell)
	if err != nil {
		t.Fatalf("get(%s): %v", cell, err)
	}
	if got != want {
		t.Errorf("get(%s): got %q, want %q", cell, got, want)
	}
}

func record(t *testing.T, cell, in, out string, ts uint64) string {
	t.Helper()
	seal, err := LedgerRecord(cell, in, out, ts)
	if err != nil {
		t.Fatalf("ledger_record(%s): %v", cell, err)
	}
	return seal
}

func reconcileContains(t *testing.T, cell string, needles ...string) string {
	t.Helper()
	report, err := LedgerReconcile(cell)
	if err != nil {
		t.Fatalf("ledger_reconcile(%s): %v", cell, err)
	}
	for _, n := range needles {
		if !strings.Contains(report, n) {
			t.Errorf("reconcile(%s) missing %s\n got: %s", cell, n, report)
		}
	}
	return report
}

func verifyIs(t *testing.T, cell string, want bool) {
	t.Helper()
	got, err := LedgerVerify(cell)
	if err != nil {
		t.Fatalf("ledger_verify(%s): %v", cell, err)
	}
	if got != want {
		t.Errorf("ledger_verify(%s): got %v, want %v", cell, got, want)
	}
}

func closeEnough(t *testing.T, what string, got, want float64) {
	t.Helper()
	if math.Abs(got-want) > 1e-12 {
		t.Errorf("%s: got %v, want %v", what, got, want)
	}
}

func TestAbiVersion(t *testing.T) {
	if got, want := AbiVersion(), HeaderAbiVersion(); got != want {
		t.Fatalf("ABI version: got %d, want %d", got, want)
	}
}

func TestOpAValueRead(t *testing.T) {
	e := newGoldenEngine(t)
	getIs(t, e, "bilge.threshold", "80.0")
	getIs(t, e, "status", `"idle"`)
	getIs(t, e, "bilge.level", "40.0")
}

func TestOpBFormulaEvalReactive(t *testing.T) {
	e := newGoldenEngine(t)
	getIs(t, e, "pump.should_run", "false")
	getIs(t, e, "pump.relay_cmd", "-20.0")
	if err := e.Set("bilge.level", "85.0"); err != nil {
		t.Fatalf("push bilge.level=85.0: %v", err)
	}
	getIs(t, e, "bilge.level", "85.0")
	getIs(t, e, "pump.should_run", "true")
	getIs(t, e, "pump.relay_cmd", "2.5")
}

func TestOpDEdges(t *testing.T) {
	LedgersReset()

	// -- wire edge (a la wasm conformance op (d)) ------------------------

	// scalar-bilge-edge: delta 45.0, imbalance 45.0.
	closeEnough(t, "(d) scalar delta", wireDeltaScalar(40.0, 85.0), 45.0)
	closeEnough(t, "(d) scalar imbalance", wireImbalanceScalar(40.0, 85.0), 45.0)
	if got, want := provenance("[85.0]"),
		"c488fc2a34cb70576fdb32ef7b72b0c98ee4d382813222ab518d546e7dff3d7c"; got != want {
		t.Errorf("(d) scalar provenance: got %s, want %s", got, want)
	}

	// vector-field-edge: delta [0.125,0.0625,0.125], imbalance 0.1875.
	gotDelta := wireDeltaVector(
		[]float64{0.25, -0.125, 0.5}, []float64{0.375, -0.0625, 0.625})
	wantDelta := []float64{0.125, 0.0625, 0.125}
	for i := range wantDelta {
		closeEnough(t, "(d) vector delta", gotDelta[i], wantDelta[i])
	}
	closeEnough(t, "(d) vector imbalance", wireImbalanceVector(
		[]float64{0.25, -0.125, 0.5}, []float64{0.375, -0.0625, 0.625}), 0.1875)
	if got, want := provenance("[[0.375,-0.0625,0.625]]"),
		"9a92df192679e9f0510defabf6e7431af3cc6ed8bc0dafbf49e19d7473e55224"; got != want {
		t.Errorf("(d) vector provenance: got %s, want %s", got, want)
	}

	// null-prior-first-edge: no prior -> delta null, imbalance null
	// (never fake a number). The null-prior ledger below pins the
	// imbalance-free reconcile: mean_surprise null.

	// -- the same edges through the ABI's ledger -------------------------

	// Scalar: bilge.level's own chain is reserved bit-for-bit for op (e),
	// so the golden values run on a twin cell; for scalars the ledger
	// surprise equals the wire imbalance (45.0).
	if err := LedgerInit("opd.scalar", "40.0", 1500); err != nil {
		t.Fatalf("ledger_init(opd.scalar): %v", err)
	}
	record(t, "opd.scalar", "85.0", "85.0", 2000)
	verifyIs(t, "opd.scalar", true)
	reconcileContains(t, "opd.scalar",
		`"entries":1`, `"total_surprise":45.0`, `"mean_surprise":45.0`,
		`"chain_intact":true`, `"balanced":true`)

	// Vector: the ABI takes uint64 millis, so the golden ts 3000.5
	// truncates to 3000; delta/imbalance are value-derived. The ledger's
	// own entry imbalance is a distance, not the wire L2 norm (that is
	// not exposed by the C ABI), so only integrity is pinned here.
	if err := LedgerInit("room.field", "[0.25,-0.125,0.5]", 2500); err != nil {
		t.Fatalf("ledger_init(room.field): %v", err)
	}
	record(t, "room.field", "[0.375,-0.0625,0.625]", "[0.375,-0.0625,0.625]", 3000)
	verifyIs(t, "room.field", true)
	reconcileContains(t, "room.field",
		`"entries":1`, `"chain_intact":true`, `"continuity_intact":true`,
		`"balanced":true`)

	// Null-prior: record without init creates the ledger without a
	// genesis, so the first edge carries no imbalance (mean_surprise
	// null), matching golden delta/imbalance null.
	record(t, "fresh.sensor", "7.0", "7.0", 5000)
	verifyIs(t, "fresh.sensor", true)
	reconcileContains(t, "fresh.sensor",
		`"entries":1`, `"mean_surprise":null`, `"open_inputs":0`,
		`"chain_intact":true`, `"balanced":true`)
	if got, want := provenance("[7.0]"),
		"e8980b1b4ea755da488add3544bf1c538901b74c0551a58de69a199baa5c4aeb"; got != want {
		t.Errorf("(d) null-prior provenance: got %s, want %s", got, want)
	}
}

func TestOpELedgerChain(t *testing.T) {
	LedgersReset()

	if err := LedgerInit("bilge.level", "40.0", 1000); err != nil {
		t.Fatalf("ledger_init genesis 40.0 @1000: %v", err)
	}
	if err := LedgerInit("bilge.level", "40.0", 1000); err == nil {
		t.Error("double ledger_init must be rejected")
	}

	root, err := LedgerChainHash("bilge.level")
	if err != nil {
		t.Fatalf("chain_hash (genesis root): %v", err)
	}
	if root != gGenesisRoot {
		t.Errorf("genesis root: got %s, want %s", root, gGenesisRoot)
	}

	for i, rec := range []struct {
		seal string
		val  string
		ts   uint64
	}{
		{gEntry1, "85.0", 2000},
		{gEntry2, "87.5", 3000},
		{gEntry3, "87.5", 4000},
	} {
		if got := record(t, "bilge.level", rec.val, rec.val, rec.ts); got != rec.seal {
			t.Errorf("seal %d bit-for-bit: got %s, want %s", i+1, got, rec.seal)
		}
	}

	verifyIs(t, "bilge.level", true)
	if _, err := LedgerVerify("no.such.cell"); err == nil {
		t.Error("unknown ledger must return an error (-1)")
	}

	head, err := LedgerChainHash("bilge.level")
	if err != nil {
		t.Fatalf("chain_hash: %v", err)
	}
	if head != gChainHash {
		t.Errorf("chain_hash: got %s, want %s", head, gChainHash)
	}
	t.Logf("chain_hash = %s", head)

	reconcileContains(t, "bilge.level", gReconcileNeedles...)
}

func TestErrorDiscipline(t *testing.T) {
	e := newGoldenEngine(t)

	if _, err := e.Get("no.such.cell"); err == nil {
		t.Error("unknown cell must return an error")
	} else if err.Error() == "" {
		t.Error("error must carry last_error detail")
	}

	var nilEngine *Engine
	if _, err := nilEngine.Get("x"); err == nil {
		t.Error("nil engine must be tolerated as an error, not a crash")
	}

	if _, err := LedgerRecord("bad.json.cell", "{not json", "1", 1); err == nil {
		t.Error("bad JSON input must return an error")
	}

	if _, err := e.Get("status"); err != nil {
		t.Fatalf("get(status) after failures: %v", err)
	}

	// The library's last_error keeps stale bytes after a successful
	// clear (verified against the C ABI directly with a C probe), so
	// ""-after-success is not assertable here; the C smoke test makes
	// the same omission.

	nilEngine.Free()
}
