#!/usr/bin/env Rscript
# test_ffi.R — golden conformance THROUGH the C ABI, base R only.
#
# Mirrors crates/quilt-cabi/smoke/smoke.c: loads the real libquilt_cabi.so
# via dyn.load and reproduces compat/golden.json ops (a)-(e):
#   (a) value read, exact JSON equality
#   (b) formula eval + reactive propagation after a sensor push
#   (d) edge delta/imbalance as sealed through the ledger (the ABI exposes
#       edge math via reconcile surprise; per docs/c-abi.md the edge itself
#       belongs to the producing tier and passes through untouched)
#   (e) ledger chain: genesis root, three seals bit-for-bit, chain_hash,
#       reconcile report
# plus the error discipline. Run:
#   ~/micromamba-envs/r/bin/Rscript bindings/r-cabi/test_ffi.R

.arg_file <- grep("^--file=", commandArgs(FALSE), value = TRUE)
.arg_dir <- if (length(.arg_file)) dirname(sub("^--file=", "", .arg_file[1])) else getwd()
script_dir <- normalizePath(.arg_dir, mustWork = FALSE)
source(file.path(script_dir, "quilt_ffi.R"))

lib_hint <- file.path(script_dir, "..", "..", "target", "release",
                      "libquilt_cabi.so")

failures <- 0L
checks <- 0L
check <- function(cond, msg) {
  checks <<- checks + 1L
  if (isTRUE(cond)) {
    cat("  PASS ", msg, "\n", sep = "")
  } else {
    failures <<- failures + 1L
    cat("  FAIL ", msg, "\n", sep = "")
  }
}

# Read a cell through the ABI and compare its JSON text exactly.
get_is <- function(engine, cell, want) {
  got <- quilt_take(quilt_engine_get(engine, cell))
  if (is.null(got)) {
    cat("    get(", cell, ") returned NULL: ", quilt_last_error(), "\n", sep = "")
    return(FALSE)
  }
  ok <- identical(got, want)
  if (!ok) cat("    get(", cell, "): got '", got, "', want '", want, "'\n", sep = "")
  ok
}

# Every needle must appear in the JSON report (fixed strings, plus optional
# regex needles for values golden.json does not pin byte-exactly).
report_has <- function(report, needles, regex = character(0)) {
  ok <- !is.null(report)
  if (ok) for (n in needles) if (!grepl(n, report, fixed = TRUE)) {
    cat("    reconcile missing ", n, "\n    got: ", report, "\n", sep = "")
    ok <- FALSE
  }
  if (ok) for (p in regex) if (!grepl(p, report)) {
    cat("    reconcile missing /", p, "/\n    got: ", report, "\n", sep = "")
    ok <- FALSE
  }
  ok
}

# -- golden vectors (compat/golden.json; same source as smoke/golden_vectors.h)

SHEET_YAML <- paste(c(
  "# GENERATED by smoke/gen-sheet.py from compat/golden.json — do not edit.",
  "# The golden sheet; every cell id, kind, and dependency edge is part",
  "# of the quilt-compat/1 contract.",
  'id: "bilge-reflex"',
  'description: "The golden sheet: a sensor, a threshold, two formulas, a status value. Every cell id, kind, and dependency edge below is part of the contract."',
  "cells:",
  '  - id: "bilge.level"',
  '    kind: "sensor"',
  '    source: "simulated"',
  "    default: 40.0",
  '  - id: "bilge.threshold"',
  '    kind: "value"',
  "    value: 80.0",
  '  - id: "pump.should_run"',
  '    kind: "formula"',
  '    expr: "=bilge.level >= bilge.threshold"',
  '  - id: "pump.relay_cmd"',
  '    kind: "formula"',
  '    expr: "=clamp((bilge.level - bilge.threshold) * 0.5, -30.0, 30.0)"',
  '  - id: "status"',
  '    kind: "value"',
  '    value: "idle"'
), collapse = "\n")
SHEET_YAML <- paste0(SHEET_YAML, "\n")

G_ENTRY1_PREV <- "470bc52774d2c173c46c5b0a8733676500fbc3b0b0cbf6d3e57662ff2ac4c1d3"
G_ENTRY1 <- "00b88886f4a22747e7e546144d18af42605c34e2ba07d3040ba18d6f24ce3f30"
G_ENTRY2 <- "3f3a94eb2e88c0e3bddfc8dfcb5554af2fe7b5cd80e20ac0ff972ae7a31caa3d"
G_ENTRY3 <- "4a7ad64830d5c2a843bf7b6f4d7253d43f2603753611fe58f0bb7c4d87ea62b8"
G_CHAIN_HASH <- "4a7ad64830d5c2a843bf7b6f4d7253d43f2603753611fe58f0bb7c4d87ea62b8"

G_RECONCILE_NEEDLES <- c(
  '"cell_id":"bilge.level"', '"entries":3', '"open_inputs":0',
  '"matched_pairs":3', '"chain_intact":true', '"continuity_intact":true',
  '"balanced":true', '"total_surprise":47.5',
  '"mean_surprise":15.833333333333334')

cat("=== quilt-cabi R FFI (dyn.load + .Call over libquilt_cabi.so) ===\n")

ok <- tryCatch({
  quilt_cabi_load(if (file.exists(lib_hint)) lib_hint else NULL)
  TRUE
}, error = function(e) { cat("    load failed: ", conditionMessage(e), "\n", sep = ""); FALSE })
check(ok, "dyn.load libquilt_cabi.so + build SEXP adapter")
if (!ok) {
  cat("RESULT: FAIL — ", checks, " checks, ", failures + 1L, " failures\n", sep = "")
  quit(save = "no", status = 1L)
}
cat("  lib:  ", .quilt$lib, "\n", sep = "")
cat("  shim: ", .quilt$shim_path, "\n", sep = "")

check(identical(quilt_abi_version(), 1L), "ABI version matches quilt_cabi.h")

check(identical(quilt_ledgers_reset(), 0L), "ledgers_reset (clean slate)")

# -- engine + golden sheet ---------------------------------------------------

engine <- quilt_engine_new()
check(!is.null(engine), "engine_new")
check(identical(quilt_engine_load_sheet(engine, SHEET_YAML), 0L),
      "load_sheet (golden YAML)")

# -- op (a): value cell read — exact JSON equality ---------------------------

check(get_is(engine, "bilge.threshold", "80.0"), "(a) read bilge.threshold == 80.0")
check(get_is(engine, "status", "\"idle\""), "(a) read status == \"idle\"")
check(get_is(engine, "bilge.level", "40.0"), "(a) read bilge.level == 40.0")

# -- op (b): formula eval, initial + post-push --------------------------------

check(get_is(engine, "pump.should_run", "false"), "(b) initial should_run == false")
check(get_is(engine, "pump.relay_cmd", "-20.0"), "(b) initial relay_cmd == -20.0")
check(identical(quilt_engine_set(engine, "bilge.level", "85.0"), 0L),
      "(b) push level=85.0")
check(get_is(engine, "bilge.level", "85.0"), "(b) post level == 85.0")
check(get_is(engine, "pump.should_run", "true"), "(b) post should_run == true")
check(get_is(engine, "pump.relay_cmd", "2.5"), "(b) post relay_cmd == 2.5")

# -- op (d): edge delta/imbalance, sealed through the ledger ------------------
# The ABI exposes edge math via the ledger: a genesis 40.0 then an edge to
# 85.0 must score imbalance |85 - 40| = 45 (golden op_d scalar-bilge-edge:
# delta 45.0, imbalance 45.0), and a null-prior first edge must claim no
# surprise at all (never fake a number).

check(identical(quilt_ledger_init("edge.scalar", "40.0", 1000), 0L),
      "(d) ledger_init genesis 40.0 @1000")
seal <- quilt_take(quilt_ledger_record("edge.scalar", "85.0", "85.0", 2000))
check(!is.null(seal), "(d) record 40.0 -> 85.0 edge sealed")
check(identical(quilt_ledger_verify("edge.scalar"), 1L),
      "(d) edge ledger chain verifies (1)")
rep_d <- quilt_take(quilt_ledger_reconcile("edge.scalar"))
check(report_has(rep_d, c('"entries":1', '"matched_pairs":1', '"balanced":true',
                          '"total_surprise":45.0', '"mean_surprise":45.0')),
      "(d) delta/imbalance 45.0 through reconcile")

check(!is.null(quilt_take(quilt_ledger_record("edge.fresh", "7.0", "7.0", 5000))),
      "(d) null-prior first edge sealed (no genesis)")
check(identical(quilt_ledger_verify("edge.fresh"), 1L),
      "(d) null-prior ledger chain verifies (1)")
rep_n <- quilt_take(quilt_ledger_reconcile("edge.fresh"))
# golden.json does not pin an unscored ledger; the reference core sums to a
# magnitude-zero total (rendered -0.0) and reports mean null — never a faked
# number. Assert exactly that.
check(report_has(rep_n, c('"entries":1', '"matched_pairs":1', '"balanced":true',
                          '"mean_surprise":null'),
                 regex = '"total_surprise":-?0[.]0'),
      "(d) null prior claims no surprise (delta/imbalance null, never faked)")

# -- op (e): ledger record / verify / reconcile, seals bit-for-bit -------------

check(identical(quilt_ledger_init("bilge.level", "40.0", 1000), 0L),
      "(e) ledger_init genesis 40.0 @1000")
check(identical(quilt_ledger_init("bilge.level", "40.0", 1000), -1L),
      "(e) double ledger_init is rejected")

# The empty ledger's chain hash is the genesis commit — the golden root that
# entry 1's prev-link seals against. Explicit decode-then-free, the memory
# contract in full view.
root_ptr <- quilt_ledger_chain_hash("bilge.level")
root <- quilt_read_string(root_ptr)
quilt_string_free(root_ptr)
check(identical(root, G_ENTRY1_PREV), "(e) genesis root pinned")

s1 <- quilt_take(quilt_ledger_record("bilge.level", "85.0", "85.0", 2000))
s2 <- quilt_take(quilt_ledger_record("bilge.level", "87.5", "87.5", 3000))
s3 <- quilt_take(quilt_ledger_record("bilge.level", "87.5", "87.5", 4000))
check(identical(s1, G_ENTRY1), "(e) seal 1 bit-for-bit")
check(identical(s2, G_ENTRY2), "(e) seal 2 bit-for-bit")
check(identical(s3, G_ENTRY3), "(e) seal 3 bit-for-bit")

check(identical(quilt_ledger_verify("bilge.level"), 1L), "(e) chain verifies (1)")
check(identical(quilt_ledger_verify("no.such.cell"), -1L), "(e) unknown ledger -> -1")

check(identical(quilt_take(quilt_ledger_chain_hash("bilge.level")), G_CHAIN_HASH),
      "(e) chain_hash == golden head (bit-for-bit)")

rep <- quilt_take(quilt_ledger_reconcile("bilge.level"))
check(report_has(rep, G_RECONCILE_NEEDLES), "(e) reconcile report matches golden")

# -- error discipline ----------------------------------------------------------

check(is.null(quilt_engine_get(engine, "no.such.cell")),
      "unknown cell returns NULL")
check(nzchar(quilt_last_error()), "last_error explains the failure")
check(is.null(quilt_engine_get(NULL, "x")), "NULL engine tolerated")
check(is.null(quilt_ledger_record("x.cell", "{not json", "1", 1)),
      "bad JSON input returns NULL")

# -- clean shutdown -------------------------------------------------------------

quilt_engine_free(engine)
quilt_string_free(NULL)  # must be a no-op
invisible(quilt_ledgers_reset())

cat("chain_hash: ", G_CHAIN_HASH, "\n", sep = "")
cat("RESULT: ", if (failures == 0L) "PASS" else "FAIL", " — ", checks,
    " checks, ", failures, " failures\n", sep = "")
quit(save = "no", status = if (failures == 0L) 0L else 1L)
